name: Produção

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: run-application 

    steps:
    - name: Verifica Códigos
      uses: actions/checkout@v2

    - name: Atualiza Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Instala Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy da Aplicação
      run: |
        # Coloque aqui os comandos necessários para fazer o deploy da sua aplicação para produção
        # Exemplo: rsync, scp, git pull, etc.
        echo "Deploying to production..."
